version: "3.8"

services:
  backend:
    build: 
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - shecodes_network

  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:5000
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - shecodes_network
    command: npm run dev -- --host

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - shecodes_network
    volumes:
      - mongo_data:/data/db

networks:
  shecodes_network:

volumes:
  mongo_data:
